spring:
  application:
    name: turbin
  rabbitmq:
    host: 192.168.88.140
    port: 5672
    username: admin
    password: admin
    
server:
  port: 5001
  
eureka:
  client:
    service-url:
      defaultZone: http://eureka1:2001/eureka, http://eureka2:2002/eureka
      
turbine:
  app-config: order-service, zuul #feign #监控服务器的名字
  cluster-name-expression: new String("default") #给上面监控服务器组成的集群起一个名字
